### ISSUE TITLE
NullPointerException on player death

### ISSUE THREAD

**Issue by Diranus** [ExceptedPrism3/Logger#35]
**Describe the bug**
NullPointerException on player death

**To Reproduce**
1. Die
2. See log

**Expected behavior**
No exception. 

**Screenshots**
`[22:15:56] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to Logger v1.8.0.4
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at me.prism3.logger.events.OnPlayerDeath.onDeath(OnPlayerDeath.java:78) ~[Logger-Spigot-1.8.0.4.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor378.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-386]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:907) ~[paper-1.19.3.jar:git-Paper-386]
	at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:908) ~[?:?]`

**Server & Version (please complete the following information):**
 - Version 1.19.3
 - Paper

**Comment by ExceptedPrism3** [comment]
Hello, will be fixed in the upcoming release!
