### ISSUE TITLE
java.lang.NoSuchFieldError: org/bukkit/Material.SHULKER_BOX

### ISSUE THREAD

**Issue by NeglectDream** [ExceptedPrism3/Logger#41]
**Describe the bug**
Download the latest version of the plugin, but there was an error when it was loaded and started
`
[19:02:29] [Server thread/INFO]: [Logger] Enabling Logger v1.8.0.9
[19:02:29] [Server thread/ERROR]: Error occurred while enabling Logger v1.8.0.9 (Is it up to date?)
java.lang.NoSuchFieldError: org/bukkit/Material.SHULKER_BOX
	at me.prism3.logger.events.oninventories.OnChestInteraction.addAdditionalItems(OnChestInteraction.java:48) ~[?:?]
	at me.prism3.logger.events.oninventories.OnChestInteraction.<init>(OnChestInteraction.java:73) ~[?:?]
	at me.prism3.logger.Main.eventsInitializer(Main.java:169) ~[?:?]
	at me.prism3.logger.Main.onEnable(Main.java:77) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1620]
	at top.iseason.bukkit.model.PLoader.enablePlugin(PLoader.java:134) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_282]
[19:02:29] [Server thread/INFO]: [Logger] Disabling Logger v1.8.0.9
[19:02:29] [Server thread/ERROR]: Could not pass event PluginDisableEvent to PlaceholderAPI v2.8.7
org.bukkit.event.EventException: null
	at top.iseason.bukkit.model.PLoader.lambda$createRegisteredListeners$1(PLoader.java:113) ~[?:?]
	at top.iseason.bukkit.model.PLoader$$Lambda$1281/0x00000000c835d600.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36) ~[patched_1.12.2.jar:git-Paper-1620]
	at top.iseason.bukkit.listener.PLTimedRegisteredListener.callEvent(PLTimedRegisteredListener.java:28) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:333) ~[patched_1.12.2.jar:git-Paper-1620]
	at top.iseason.bukkit.model.PLoader.disablePlugin(PLoader.java:129) ~[?:?]
	at org.bukkit.plugin.PluginLoader.disablePlugin(PluginLoader.java:88) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) ~[patched_1.12.2.jar:git-Paper-1620]
	at top.iseason.bukkit.model.PLoader.enablePlugin(PLoader.java:134) ~[?:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:823) [?:1.8.0_282]
Caused by: java.lang.AbstractMethodError: me/clip/placeholderapi/expansion/PlaceholderExpansion.getPlugin()Ljava/lang/String;
	at me.clip.placeholderapi.PlaceholderListener.onPluginUnload(PlaceholderListener.java:125) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_282]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_282]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at top.iseason.bukkit.model.PLoader.lambda$createRegisteredListeners$1(PLoader.java:111) ~[?:?]
	... 21 more
`

**Server & Version (please complete the following information):**
 - Version 1.8.0.9
 - Server Type Spigot 1.12.2

**Comment by DICEALPHAHU** [comment]
已经收到你的反馈，正在全力排查中
依照代码报错判断，极有可能是潜影盒导致ChestLogger事件报错，
已经提交到未来bug修复中，还劳烦你的等待。^_^

Your feedback has been received, and it is under investigation
According to the code, it is most likely that the shulker box caused the ChestLogger event to report an error.
It has been committed to future bug fixes, plz wait. :)

**Comment by NeglectDream** [comment]
> 已经收到你的反馈，正在全力排查中 依照代码报错判断，极有可能是潜影盒导致ChestLogger事件报错， 已经提交到未来bug修复中，还劳烦你的等待。^_^
> 
> Your feedback has been received, and it is under investigation According to the code, it is most likely that the shulker box caused the ChestLogger event to report an error. It has been committed to future bug fixes, plz wait. :)

感谢对我的重视，我尝试退回了两个版本，现在可以正常使用了，期待新版本！

**Comment by ExceptedPrism3** [comment]
The following issue has been fixed and will be included in the upcoming release.
