### ISSUE TITLE
cannot used in 1.20.6

### ISSUE THREAD

**Issue by DICEALPHAHU** [ExceptedPrism3/Logger#53]
**Describe the bug**
up to date

**Detail**
[Logger] Enabling Logger v1.8.0.13
[22:28:41 ERROR]: Error occurred while enabling Logger v1.8.0.13 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at 【服务器监控】Logger-Spigot-1.8.0.13.jar/me.prism3.logger.utils.Data.versionChecker(Data.java:175) ~[【服务器监控】Logger-Spigot-
1.8.0.13.jar:?]
        at 【服务器监控】Logger-Spigot-1.8.0.13.jar/me.prism3.logger.utils.Data.initializeIntegers(Data.java:136) ~[【服务器监控】Logger-Spi
got-1.8.0.13.jar:?]
        at 【服务器监控】Logger-Spigot-1.8.0.13.jar/me.prism3.logger.utils.Data.initializer(Data.java:87) ~[【服务器监控】Logger-Spigot-1.8.
0.13.jar:?]
        at 【服务器监控】Logger-Spigot-1.8.0.13.jar/me.prism3.logger.Main.onEnable(Main.java:51) ~[【服务器监控】Logger-Spigot-1.8.0.13.jar:
?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[purpur-1.20.6.jar:
git-Purpur-2183]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:git-Purp
ur-2183]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:565) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:685) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:444) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:358) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1154) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:28:41 INFO]: [Logger] Disabling Logger v1.8.0.13
[22:28:41 ERROR]: Error occurred while disabling Logger v1.8.0.13
java.lang.NullPointerException: Cannot invoke "me.prism3.logger.manager.Messages.get()" because the return value of "me.prism3.logger.Main.g
etMessages()" is null
        at 【服务器监控】Logger-Spigot-1.8.0.13.jar/me.prism3.logger.serverside.Stop.run(Stop.java:42) ~[【服务器监控】Logger-Spigot-1.8.0.1
3.jar:?]
        at 【服务器监控】Logger-Spigot-1.8.0.13.jar/me.prism3.logger.Main.onDisable(Main.java:103) ~[【服务器监控】Logger-Spigot-1.8.0.13.ja
r:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[purpur-1.20.6.jar
:git-Purpur-2183]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[purpur-1.20.6.jar:git-Pur
pur-2183]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[purpur-1.20.6.jar:
git-Purpur-2183]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.6.jar:git-Purp
ur-2183]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[purpur-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:565) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:685) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:444) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:358) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1154) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[purpur-1.20.6.jar:git-Purpur-2183]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Server & Version (please complete the following information):**
 - Version 1.8.0.13
 - Server Type [Spigot]

**Comment by ExceptedPrism3** [comment]
Hello there,

Thanks for the report.

It has been fixed in the latest current version: **1.8.0.14**.
