### ISSUE TITLE
Task #1240231 for Logger v1.8.0.15 generated an exception

### ISSUE THREAD

**Issue by mateuscolli** [ExceptedPrism3/Logger#59]
**Describe the bug**
I just installed the plugin and the following error started appearing in the console:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "java.util.HashMap.get(Object)" is null
at Logger-1.8.0.15-1729519575599.jar/me.prism3.logger.events.plugindependent.OnVault.run(OnVault.java:48) ~[Logger-1.8.0.15-1729519575599.jar:?]
at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2304-dee41bc] at org.bukit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[purpur-1.21.1.jar:1.21.1-2304-dee41bc] at net.minecraft.server. MinecraftServer.tickChildren(MinecraftServer.java:1763) ~[purpur-1.21.1.jar:1.21.1-2304-dee41bc] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2304-dee41bc] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1635) ~[purpur-1.21.1.jar:1.21.1-2304-dee41bc] er.java:1335) ~[purpur-1.21.1.jar:1.21.1-2304-dee41bc] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:334) ~[purpur-1.21.1.jar:1.21.1-2304-dee41bc] at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**To reproduce**
1. Server purpur-1.21.1-2304
2. I just installed the plugin, without any extra configuration.

**Expected behavior**
It should work without any errors.

**Screenshots**

**Server and version (fill in the following information):**
- Version 1.21
- Server type: with Bungeecord proxy

**Comment by ExceptedPrism3** [comment]
This issue was fixed and will be included in the upcoming release.
