### ISSUE TITLE
Spamming: [Server thread/ERROR]: Could not pass event PlayerPickupItemEvent to Logger v1.8.0.15

### ISSUE THREAD

**Issue by MarioPEgamer** [ExceptedPrism3/Logger#60]
Recently (today) the following message has been spammed in the server log:

[15:44:56] [Server thread/ERROR]: Could not pass event PlayerDropItemEvent to Logger v1.8.0.15
java.lang.IllegalArgumentException: No enum constant me.prism3.logger.utils.enums.FriendlyEnchants.nova_structures:wither_coated
at java.base/java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
at Logger-1.8.0.15.jar/me.prism3.logger.utils.enums.FriendlyEnchants.valueOf(FriendlyEnchants.java:5) ~[Logger-1.8.0.15.jar:?]
at Logger-1.8.0.15.jar/me.prism3.logger.utils.enums.FriendlyEnchants.getFriendlyEnchantment(FriendlyEnchants.java:60) ~[Logger-1.8.0.15.jar:?]
at Logger-1.8.0.15.jar/me.prism3.logger.events.OnItemDrop.lambda$onDrop$0(OnItemDrop.java:61) ~[Logger-1.8.0.15.jar:?]
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
at com.google.common.collect.CollectSpliterators$1WithCharacteristics.lambda$forEachRemaining$1(CollectSpliterators.java:72) ~[guava-32.1.2-jre.jar:?]
at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104) ~[?:?]
at com.google.common.collect.CollectSpliterators$1WithCharacteristics.forEachRemaining(CollectSpliterators.java:72) ~[guava-32.1.2-jre.jar:?]
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
at Logger-1.8.0.15.jar/me.prism3.logger.events.OnItemDrop.onDrop(OnItemDrop.java:64) ~[Logger-1.8.0.15.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor38.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-118-fb76840]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.world.entity.player.Player.drop(Player.java:793) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2577) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.server.level.ServerPlayer.drop(ServerPlayer.java:2572) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.world.entity.player.Player.drop(Player.java:734) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:652) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:382) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3232) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-118-fb76840]
at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

I asked on the server what is being going on and a player said he is fighting the Wither in the Nether.

I have no exact idea if and how the whole thing can be reproduced.

Information and attachments: 

Server: 
Paper version 1.21.1-118-master@fb76840

Level Seed: 
LeKaRo

Plugins used:
[RealTimePlugin 3.9](https://www.spigotmc.org/resources/real-time-plugin.69545/)
[PluginPortal 2.0.4](https://www.spigotmc.org/resources/plugin-portal.108700/)
[Logger 1.8.0.15](https://www.spigotmc.org/resources/logger-1-7-1-21.94236/)
[JoinMessagePlus 3.3](https://dev.bukkit.org/projects/join-message-plus)
[Geyser Spigot](https://geysermc.org/) (no Bedrock player was online at this time)
[floodgate spigot](https://geysermc.org/)
[EasyRules](https://dev.bukkit.org/projects/easyrules)
[ViaVersions 5.0.4-Snapshot+532](https://modrinth.com/plugin/viaversion)
[Simple Voice Chat bukkit 2.5.20](https://modrinth.com/plugin/simple-voice-chat)
[LuckPerms 5.4.131](https://www.spigotmc.org/resources/luckperms.28140/)
[ChestSort 14.1.0](https://www.spigotmc.org/resources/chestsort-api.59773/)

DataPacks used:
[Amplified Nether 1.21 v1.2.5](https://modrinth.com/datapack/amplified-nether)
[Continents 1.21 v1.1.5](https://modrinth.com/datapack/continents)
[Dungeons and Taverns v4.4.4](https://modrinth.com/datapack/dungeons-and-taverns)
[Nullscape 1.21 v1.2.8](https://modrinth.com/datapack/nullscape)
[Structory 1.21 v1.3.5](https://modrinth.com/datapack/structory)
[Structory Towers 1.21 v1.0.7](https://modrinth.com/datapack/structory-towers)
[Terralith 1.21 v2.5.5](https://modrinth.com/datapack/terralith)

I will attach the following files to this bug report:
[Logger Pickup item: 22-10-2024.log](https://github.com/user-attachments/files/17477632/22-10-2024.log)
[latest.log](https://github.com/user-attachments/files/17477633/latest.log)

**Comment by ExceptedPrism3** [comment]
This issue has been resolved, will be implemented in the upcoming 1.8.1 version.
