### ISSUE TITLE
Stacktrace: Missing permission: MESSAGE_WRITE

### ISSUE THREAD

**Issue by Boastful1353** [ExceptedPrism3/Logger#61]
**Describe the bug**
Attempting to log commands throws a stacktrace.

**To Reproduce**
Install & Test plugin with supplied plugins and server version
run a command for it to log

**Expected behavior**
A log entry should be made

**Screenshots**
`[16:40:16 ERROR]: Could not pass event PlayerCommandPreprocessEvent to Logger v1.8.0.15
me.prism3.net.dv8tion.jda.api.exceptions.InsufficientPermissionException: Cannot perform action due to a lack of Permission. Missing permission: MESSAGE_WRITE
        at Logger-1.8.0.15.jar/me.prism3.net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:329) ~[Logger-1.8.0.15.jar:?]
        at Logger-1.8.0.15.jar/me.prism3.net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:320) ~[Logger-1.8.0.15.jar:?]
        at Logger-1.8.0.15.jar/me.prism3.net.dv8tion.jda.internal.entities.TextChannelImpl.sendMessage(TextChannelImpl.java:357) ~[Logger-1.8.0.15.jar:?]
        at Logger-1.8.0.15.jar/me.prism3.logger.discord.Discord.discordUtil(Discord.java:710) ~[Logger-1.8.0.15.jar:?]
        at Logger-1.8.0.15.jar/me.prism3.logger.discord.Discord.playerCommand(Discord.java:449) ~[Logger-1.8.0.15.jar:?]
        at Logger-1.8.0.15.jar/me.prism3.logger.events.oncommands.OnCommand.onPlayerCmd(OnCommand.java:137) ~[Logger-1.8.0.15.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor195.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2183) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$11(ServerGamePacketListenerImpl.java:2170) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1448) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1428) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1422) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1379) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1387) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.4.jar:1.21.4-30-aa2c52b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Server & Version (please complete the following information):**
This server is running Paper version 1.21.4-30-main@aa2c52b (2024-12-23T19:28:24Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

\*AdvancedLogin, AngelChest, chocofly, CoreProtect, CreativeManager, Essentials, EssentialsChat, EssentialsDiscord, EssentialsDiscordLink, EssentialsGeoIP
EssentialsSpawn, FrogRTP, GriefPrevention, LiteBans, Logger, LuckPerms, mcMMO, sleep-most, Vault, WorldEdit
WorldEditSUI

**Comment by httphypixelnet** [comment]
Hi. Could you please double-check your bot has the correct permissions in the server you set in the config?
If it has the correct permissions, please run `/logger dump` and send the generated link in the Discord ticket you made.

**Comment by Boastful1353** [comment]
Setting the bot to admin corrected the issue. I prefer to run bots without admin access. I will try to narrow down the necessary permissions. Do you have any advice on this subject or do you have it hard coded to only work with administrator?

**Comment by httphypixelnet** [comment]
It shouldn't require administrator to work. I'll get to work on making a list of required permissions.

**Comment by ExceptedPrism3** [comment]
The following error has been resolved, it will be present in the upcoming release.
